import { BitField } from './BitField';

export const enum PermissionsFlags {
	CREATE_INSTANT_INVITE,
	KICK_MEMBERS,
	BAN_MEMBERS,
	ADMINISTRATOR,
	MANAGE_CHANNELS,
	MANAGE_GUILD,
	ADD_REACTIONS,
	VIEW_AUDIT_LOG,
	PRIORITY_SPEAKER,
	STREAM,
	VIEW_CHANNEL,
	SEND_MESSAGES,
	SEND_TTS_MESSAGES,
	MANAGE_MESSAGES,
	EMBED_LINKS,
	ATTACH_FILES,
	READ_MESSAGE_HISTORY,
	MENTION_EVERYONE,
	USE_EXTERNAL_EMOJIS,
	VIEW_GUILD_INSIGHTS,
	CONNECT,
	SPEAK,
	MUTE_MEMBERS,
	DEAFEN_MEMBERS,
	MOVE_MEMBERS,
	USE_VAD,
	CHANGE_NICKNAME,
	MANAGE_NICKNAMES,
	MANAGE_ROLES,
	MANAGE_WEBHOOKS,
	MANAGE_EMOJIS,
}

export class Permissions extends BitField<PermissionsFlags> {
	public static readonly FLAGS = {
		[PermissionsFlags.CREATE_INSTANT_INVITE]: 1 << 0,
		[PermissionsFlags.KICK_MEMBERS]: 1 << 1,
		[PermissionsFlags.BAN_MEMBERS]: 1 << 2,
		[PermissionsFlags.ADMINISTRATOR]: 1 << 3,
		[PermissionsFlags.MANAGE_CHANNELS]: 1 << 4,
		[PermissionsFlags.MANAGE_GUILD]: 1 << 5,
		[PermissionsFlags.ADD_REACTIONS]: 1 << 6,
		[PermissionsFlags.VIEW_AUDIT_LOG]: 1 << 7,
		[PermissionsFlags.PRIORITY_SPEAKER]: 1 << 8,
		[PermissionsFlags.STREAM]: 1 << 9,
		[PermissionsFlags.VIEW_CHANNEL]: 1 << 10,
		[PermissionsFlags.SEND_MESSAGES]: 1 << 11,
		[PermissionsFlags.SEND_TTS_MESSAGES]: 1 << 12,
		[PermissionsFlags.MANAGE_MESSAGES]: 1 << 13,
		[PermissionsFlags.EMBED_LINKS]: 1 << 14,
		[PermissionsFlags.ATTACH_FILES]: 1 << 15,
		[PermissionsFlags.READ_MESSAGE_HISTORY]: 1 << 16,
		[PermissionsFlags.MENTION_EVERYONE]: 1 << 17,
		[PermissionsFlags.USE_EXTERNAL_EMOJIS]: 1 << 18,
		[PermissionsFlags.VIEW_GUILD_INSIGHTS]: 1 << 19,
		[PermissionsFlags.CONNECT]: 1 << 20,
		[PermissionsFlags.SPEAK]: 1 << 21,
		[PermissionsFlags.MUTE_MEMBERS]: 1 << 22,
		[PermissionsFlags.DEAFEN_MEMBERS]: 1 << 23,
		[PermissionsFlags.MOVE_MEMBERS]: 1 << 24,
		[PermissionsFlags.USE_VAD]: 1 << 25,
		[PermissionsFlags.CHANGE_NICKNAME]: 1 << 26,
		[PermissionsFlags.MANAGE_NICKNAMES]: 1 << 27,
		[PermissionsFlags.MANAGE_ROLES]: 1 << 28,
		[PermissionsFlags.MANAGE_WEBHOOKS]: 1 << 29,
		[PermissionsFlags.MANAGE_EMOJIS]: 1 << 30,
	} as const;
}
